services:
  app:
    image: {{DOCKER_USERNAME}}/coders-online:latest
    container_name: dotnet_app
    ports:
      - "5000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server={{DB_SERVER}};Database={{DB_NAME}};User Id={{DB_USER}};Password={{DB_PASSWORD}};