services:
  app:
    image: {{DOCKER_USERNAME}}/coders-online:latest
    container_name: dotnet_app
    ports:
      - "5000:5000" 
      - "44358:44358" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection={{CONNECTION_STRING}};