services:
  app:
    image: {{DOCKER_USERNAME}}/coders-online:latest
    container_name: dotnet_app
    ports:
      - "5000:5000" 
      - "44358:44358" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_SERVER={{DB_SERVER}}
      - DB_USER={{DB_USER}}
      - DB_PASSWORD={{DB_PASSWORD}}
      - DB_NAME={{DB_NAME}}